config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  resources :orders do
    collection do
      get :search
    end
  end
  resources :tariffs
  resources :automobiles
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :automobile
  belongs_to :tariff

  validate :time_of_travel_cannot_be_in_the_past
  validates :departure_address, length: {minimum: 10, maximum: 64}
  validates :arrival_address, length: {minimum: 10, maximum: 64}
  validates :number_of_passengers, numericality: {greater_than_or_equal_to: 1}
  validates :length_of_route, numericality: {greater_than_or_equal_to: 1}
  validates :time_of_travel, :automobile_id, presence: true

  accepts_nested_attributes_for :tariff, allow_destroy: true

  # валидатор времени подачи такси:
  def time_of_travel_cannot_be_in_the_past
    if !time_of_travel.nil?
      if time_of_travel < Time.now
        errors.add(:time_of_travel, "не может быть меньше текущего времени")
      end
    end
  end

  # поиск
  def self.search(params)
    result = Order.includes(:tariff, {:automobile => :drivers}).references(:tariff, {:automobile => :drivers})

    # по атрибутам заказа:
    if params['time_of_travel_from'].present?
      result = result.where.not(time_of_travel: Time.at(0)...Time.parse(params['time_of_travel_from']))
    end
    if params['time_of_travel_to'].present?
      result = result.where(time_of_travel: Time.at(0)..Time.parse(params['time_of_travel_to']))
    end
    if params['departure_address'].present?
      result = result.where(departure_address: params['departure_address'])
    end
    if params['arrival_address'].present?
      result = result.where(arrival_address: params['arrival_address'])
    end
    if params['number_of_passengers'].present?
      result = result.where(number_of_passengers: params['number_of_passengers'])
    end
    if params['length_of_route_from'].present?
      result = result.where.not(length_of_route: 0...(params['length_of_route_from']).to_f)
    end
    if params['length_of_route_to'].present?
      result = result.where(length_of_route: 0..(params['length_of_route_to']).to_f)
    end

    # по атрибутам тарифа
    if params['tariff_name'].present?
      result = result.where(tariffs: {name: params['tariff_name']})
    end
    if params['time_of_day'].present?
      result = result.where(tariffs: {time_of_day: params['time_of_day']})
    end
    if params['range'].present?
      result = result.where(tariffs: {range: params['range']})
    end
    if params['price_per_kilometer_from'].present?
      result = result.where.not(tariffs: {price_per_kilometer: 0...(params['price_per_kilometer_from']).to_f})
    end
    if params['price_per_kilometer_to'].present?
      result = result.where(tariffs: {price_per_kilometer: 0..(params['price_per_kilometer_to']).to_f})
    end

    # по атрибутам авто:
    if params['automobile_model'].present?
      result = result.where(automobiles: {automobile_model: params['automobile_model']})
    end
    if params['automobile_type'].present?
      result = result.where(automobiles: {automobile_type: params['automobile_type']})
    end
    if params['state_number'].present?
      result = result.where(automobiles: {state_number: params['state_number']})
    end
    if params['color'].present?
      result = result.where(automobiles: {color: params['color']})
    end
    if params['release'].present?
      result = result.where(automobiles: {release: params['release']})
    end

    # по атрибутам водителя:
    if params['driver_last_name'].present?
      result = result.where(drivers: {last_name: params['driver_last_name']})
    end
    if params['driver_first_name'].present?
      result = result.where(drivers: {first_name: params['driver_first_name']})
    end
    if params['driver_patronymic'].present?
      result = result.where(drivers: {patronymic: params['driver_patronymic']})
    end
    if params['driver_date_of_birth'].present?
      result = result.where(drivers: {date_of_birth: params['driver_date_of_birth']})
    end
    if params['driver_itn'].present?
      result = result.where(drivers: {itn: params['driver_itn']})
    end
    if params['driver_passport'].present?
      result = result.where(drivers: {passport: params['driver_passport']})
    end

    result.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def search
    if params.has_key?('search')
      @orders = Order.search(params['search'])
    else
      @orders = []
    end
    params['search'] ||= {}
    @old_tariff_name      = params.has_key?('search') ? params[:search][:tariff_name] : ""
    @old_time_of_day      = params.has_key?('search') ? params[:search][:time_of_day] : ""
    @old_range            = params.has_key?('search') ? params[:search][:range] : ""
    @old_automobile_model = params.has_key?('search') ? params[:search][:automobile_model] : ""
    @old_automobile_type  = params.has_key?('search') ? params[:search][:automobile_type] : ""
    @old_color            = params.has_key?('search') ? params[:search][:color] : ""
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    # @order.build_tariff
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:time_of_travel, :departure_address, :arrival_address, :number_of_passengers, :length_of_route, :automobile_id,
      :tariff_id, tariff_attributes: [:_destroy, :id, :name, :time_of_day, :range, :price_per_kilometer])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  = error_messages_for @order
  .row
    .col-md-12
      .form-group
        = f.label :time_of_travel
        .input-group.date.datetimepicker
          = f.text_field(:time_of_travel, value: Time.now,
            class: 'form-control',
            value: nilTime(f.object.time_of_travel))
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:time_of_travel)
  .row
    .col-md-6
      .form-group
        = f.label :departure_address
        = f.text_field :departure_address, class: 'form-control'
        = f.error_messages_for(:departure_address)
    .col-md-6
      .form-group
        = f.label :arrival_address
        = f.text_field :arrival_address, class: 'form-control'
        = f.error_messages_for(:arrival_address)
  .row
    .col-md-3
      .form-group
        = f.label :number_of_passengers
        = f.number_field :number_of_passengers, class: 'form-control'
        = f.error_messages_for(:number_of_passengers)
    .col-md-3
      .form-group
        = f.label :length_of_route
        = f.text_field :length_of_route, class: 'form-control'
        = f.error_messages_for(:length_of_route)
    .col-md-6
      .form-group
        = f.label :automobile_id
        = f.select :automobile_id, options_for_select(Automobile.all.map{|x|[x.automobile_model + ": " + x.state_number + " [" + x.automobile_type + "]", x.id]},
        f.object.automobile_id),
        {include_blank: true}, {class: 'form-control'}
        = f.error_messages_for(:automobile_id)
  %div{class: 'panel panel-info'}
    .panel-heading
      .row
        .col-md-12
          .form-group
            = f.label :tariff_id
            = f.select :tariff_id,
            options_for_select(Tariff.all.map{|x|[x.name, x.id]} + (@order.new_record? ? ["*Создание нового"] : ["*Создание нового", "*Редактирование"]),
            f.object.tariff_id.nil? ? "*Создание нового" : f.object.tariff_id),
            {}, {class: 'form-control'}
            = f.error_messages_for(:tariff_id)
    .panel-body
      = f.fields_for :tariff, f.object.tariff || f.object.build_tariff do |df|
        %fieldset#tariff-fieldset{"data-content" => "#{render "tariff_form", df: df}"}
          %div#tariff-fields
  .actions
    = f.submit nil, class: 'btn btn-primary', id: 'save'

app/views/orders/_tariff_form.html.haml
= df.hidden_field(:id)
.row
  .col-md-6
    .form-group
      = df.label :name
      = df.text_field :name, class: 'form-control'
      = df.error_messages_for(:name)
  .col-md-6
    .form-group
      = df.label :time_of_day
      = df.select :time_of_day, ["День", "Ночь"],
      {include_blank: true}, {class: 'form-control'}
      = df.error_messages_for(:time_of_day)
.row
  .col-md-6
    .form-group
    = df.label :range
    = df.select :range, ["в пределах МКАД", "за МКАД", "Подмосковье"],
    {include_blank: true},  {class: 'form-control'}
    = df.error_messages_for(:range)
  .col-md-6
    .form-group
    = df.label :price_per_kilometer
    = df.text_field :price_per_kilometer, class: 'form-control'
    %span.input-group-addon
      %span.glyphicon.glyphicon-ruble

app/views/orders/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.orders.edit')
  %li
    = link_to(@order.id, @order)
  %li
    = link_to 'Заказы', orders_path
  %li
    Таксопарк

.page-header
  %h1= t('headers.orders.edit')

= render 'form'

app/views/orders/index.html.haml
=breadcrumb_tag do
  %li.active
    Заказы
  %li
    Таксопарк

.page-header
  %h1= t('headers.orders.index')
-#
%table.table.table-hover.table-striped
  %caption
    = link_to new_order_path, class: 'btn btn-success' do
      = fa_icon :plus
      = t('buttons.new.order')
    = link_to search_orders_path, class: 'btn btn-info' do
      = fa_icon :search
      = t('buttons.search.order')

- @orders.each do |order|
  .alert.alert-info
    .row
      .col-md-1
        %table.table.table-hover.table-striped
          %thead
            %tr
              %th
                = Order.human_attribute_name(:id)
            %tbody
              %td.center
                = order.id
      .col-md-5
        %table.table.table-hover.table-striped
          %thead
            %tr
              %th
                = Order.human_attribute_name(:time_of_travel)
            %tbody
              %td.center
                = order.time_of_travel
      .col-md-6
        %table.table.table-hover.table-striped
          %thead
            %tr
              %th
                = Order.human_attribute_name(:automobile_id)
            %tbody
              %td.center
                = "#{order.automobile.automobile_model}, #{order.automobile.state_number} [#{order.automobile.automobile_type}]"
    .row
      .col-md-6
        %table.table.table-hover.table-striped
          %thead
            %tr
              %th
                = Order.human_attribute_name(:departure_address)
            %tbody
              %td.center
                = order.departure_address
      .col-md-6
        %table.table.table-hover.table-striped
          %thead
            %tr
              %th
                = Order.human_attribute_name(:arrival_address)
            %tbody
              %td.center
                = order.arrival_address
    .row
      .col-md-5
        %table.table.table-hover.table-striped
          %thead
            %tr
              %th
                = Order.human_attribute_name(:tariff_id)
            %tbody
              %td.center
                = "#{order.tariff.name}: #{order.tariff.time_of_day}, #{order.tariff.range}, #{order.tariff.price_per_kilometer} руб./км"
      .col-md-4
        %table.table.table-hover.table-striped
          %thead
            %tr
              %th
                = Order.human_attribute_name(:number_of_passengers)
            %tbody
              %td.center
                = order.number_of_passengers
      .col-md-3
        %table.table.table-hover.table-striped
          %thead
            %tr
              %th
                = Order.human_attribute_name(:length_of_route)
            %tbody
              %td.center
                = order.length_of_route
    .right
      = link_to order, class: 'btn btn-warning' do
        = fa_icon :eye
        = t('buttons.show')
      = link_to edit_order_path(order), class: 'btn btn-info' do
        = fa_icon :edit
        = t('buttons.edit')
      = link_to order, :method => :delete,
      :data => { :confirm => t('buttons.confirm.order') },
      class: 'btn btn-danger' do
        = fa_icon :times
        = t('buttons.destroy')

app/views/orders/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.orders.new')
  %li
    = link_to 'Заказы', orders_path
  %li
    Таксопарк

.page-header
  %h1= t('headers.orders.new')

= render 'form'

app/views/orders/search.html.haml
=breadcrumb_tag do
  %li.active
    Поиск заказов
  %li
    = link_to 'Заказы', orders_path
  %li
    Таксопарк

.page-header
  %h1= t('headers.orders.search')

= form_tag search_orders_path(), method: :get do
  %div{class: 'panel panel-info'}
    .panel-heading
      = t('forms.order_search.form.order')
    .panel-body
      .row
        .col-md-4
          .form-group
            = Order.human_attribute_name(:time_of_travel)
            .input-group.date.datetimepicker
              = text_field_tag 'search[time_of_travel_from]',
              params['search']['time_of_travel_from'],
              class: 'form-control', placeholder: t('forms.order_search.from')
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
            .input-group.date.datetimepicker
              = text_field_tag 'search[time_of_travel_to]',
              params['search']['time_of_travel_to'],
              class: 'form-control', placeholder: t('forms.order_search.to')
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
        .col-md-4
          .form-group
            = Order.human_attribute_name(:number_of_passengers)
            = text_field_tag 'search[number_of_passengers]',
            params['search']['number_of_passengers'],
            class: 'form-control'
        .col-md-4
          .form-group
            = Order.human_attribute_name(:length_of_route)
            = text_field_tag 'search[length_of_route_from]',
            params['search']['length_of_route_from'],
            class: 'form-control', placeholder: t('forms.order_search.from')
            = text_field_tag 'search[length_of_route_to]',
            params['search']['length_of_route_to'],
            class: 'form-control', placeholder: t('forms.order_search.to')
      .row
        .col-md-6
          .form-group
            = Order.human_attribute_name(:departure_address)
            = text_field_tag 'search[departure_address]',
            params['search']['departure_address'],
            class: 'form-control'
        .col-md-6
          .form-group
            = Order.human_attribute_name(:arrival_address)
            = text_field_tag 'search[arrival_address]',
            params['search']['arrival_address'],
            class: 'form-control'
  %div{class: 'panel panel-info'}
    .panel-heading
      = t('forms.order_search.form.tariff')
    .panel-body
      .row
        .col-md-3
          .form-group
            = Tariff.human_attribute_name(:name)
            = select_tag 'search[tariff_name]',
            options_for_select((Tariff.all.map{|x| [x.name, x.name]}.sort), @old_tariff_name),
            {include_blank: true, class: 'form-control'}
        .col-md-3
          .form-group
            = Tariff.human_attribute_name(:time_of_day)
            = select_tag 'search[time_of_day]',
            options_for_select((Tariff.all.map{|x| [x.time_of_day, x.time_of_day]}.uniq.sort), @old_time_of_day),
            {include_blank: true, class: 'form-control'}
        .col-md-3
          .form-group
            = Tariff.human_attribute_name(:range)
            = select_tag 'search[range]',
            options_for_select((Tariff.all.map{|x| [x.range, x.range]}.uniq.sort), @old_range),
            {include_blank: true, class: 'form-control'}
        .col-md-3
          .form-group
            = Tariff.human_attribute_name(:price_per_kilometer)
            = text_field_tag 'search[price_per_kilometer_from]',
            params['search']['price_per_kilometer_from'],
            class: 'form-control', placeholder: t('forms.order_search.from')
            = text_field_tag 'search[price_per_kilometer_to]',
            params['search']['price_per_kilometer_to'],
            class: 'form-control', placeholder: t('forms.order_search.to')
  %div{class: 'panel panel-info'}
    .panel-heading
      = t('forms.order_search.form.automobile')
    .panel-body
      .row
        .col-md-3
          .form-group
            = Automobile.human_attribute_name(:automobile_model)
            = select_tag 'search[automobile_model]',
            options_for_select((Automobile.all.map{|x| [x.automobile_model, x.automobile_model]}.uniq.sort), @old_automobile_model),
            {include_blank: true, class: 'form-control'}
        .col-md-2
          .form-group
            = Automobile.human_attribute_name(:automobile_type)
            = select_tag 'search[automobile_type]',
            options_for_select((Automobile.all.map{|x| [x.automobile_type, x.automobile_type]}.uniq.sort), @old_automobile_type),
            {include_blank: true, class: 'form-control'}
        .col-md-3
          .form-group
            = Automobile.human_attribute_name(:state_number)
            = text_field_tag 'search[state_number]',
            params['search']['state_number'],
            {include_blank: true, class: 'form-control'}
        .col-md-2
          .form-group
            = Automobile.human_attribute_name(:color)
            = select_tag 'search[color]',
            options_for_select((Automobile.all.map{|x| [x.color, x.color]}.uniq.sort), @old_color),
            {include_blank: true, class: 'form-control'}
        .col-md-2
          .form-group
            = Automobile.human_attribute_name(:release)
            = text_field_tag 'search[release]',
            params['search']['release'],
            {include_blank: true, class: 'form-control'}
  %div{class: 'panel panel-info'}
    .panel-heading
      = t('forms.order_search.form.driver')
    .panel-body
      .row
        .col-md-4
          .form-group
            = Driver.human_attribute_name(:last_name)
            = text_field_tag 'search[driver_last_name]',
            params['search']['driver_last_name'],
            class: 'form-control'
        .col-md-4
          .form-group
            = Driver.human_attribute_name(:first_name)
            = text_field_tag 'search[driver_first_name]',
            params['search']['driver_first_name'],
            class: 'form-control'
        .col-md-4
          .form-group
            = Driver.human_attribute_name(:patronymic)
            = text_field_tag 'search[driver_patronymic]',
            params['search']['driver_patronymic'],
            class: 'form-control'
      .row
        .col-md-4
          .form-group
            = Driver.human_attribute_name(:date_of_birth)
            .input-group.date.datepicker
              = text_field_tag 'search[driver_date_of_birth]',
              params['search']['driver_date_of_birth'],
              class: 'form-control'
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
        .col-md-4
          .form-group
            = Driver.human_attribute_name(:itn)
            = text_field_tag 'search[driver_itn]',
            params['search']['driver_itn'],
            class: 'form-control'
        .col-md-4
          .form-group
            = Driver.human_attribute_name(:passport)
            = text_field_tag 'search[driver_passport]',
            params['search']['driver_passport'],
            class: 'form-control'
  .actions
    = submit_tag t('buttons.search.order'), class: 'btn btn-primary'


.page-header
  %h1= t('forms.order_search.found') + ": " + @orders.size.to_s

- if @orders.size > 0
  - @orders.each do |order|
    .alert.alert-info
      .row
        .col-md-1
          %table.table.table-hover.table-striped
            %thead
              %tr
                %th
                  = Order.human_attribute_name(:id)
              %tbody
                %td.center
                  = order.id
        .col-md-5
          %table.table.table-hover.table-striped
            %thead
              %tr
                %th
                  = Order.human_attribute_name(:time_of_travel)
              %tbody
                %td.center
                  = order.time_of_travel
        .col-md-6
          %table.table.table-hover.table-striped
            %thead
              %tr
                %th
                  = Order.human_attribute_name(:automobile_id)
              %tbody
                %td.center
                  = "#{order.automobile.automobile_model}, #{order.automobile.state_number} [#{order.automobile.automobile_type}]"
      .row
        .col-md-6
          %table.table.table-hover.table-striped
            %thead
              %tr
                %th
                  = Order.human_attribute_name(:departure_address)
              %tbody
                %td.center
                  = order.departure_address
        .col-md-6
          %table.table.table-hover.table-striped
            %thead
              %tr
                %th
                  = Order.human_attribute_name(:arrival_address)
              %tbody
                %td.center
                  = order.arrival_address
      .row
        .col-md-5
          %table.table.table-hover.table-striped
            %thead
              %tr
                %th
                  = Order.human_attribute_name(:tariff_id)
              %tbody
                %td.center
                  = "#{order.tariff.name}: #{order.tariff.time_of_day}, #{order.tariff.range}, #{order.tariff.price_per_kilometer} руб./км"
        .col-md-4
          %table.table.table-hover.table-striped
            %thead
              %tr
                %th
                  = Order.human_attribute_name(:number_of_passengers)
              %tbody
                %td.center
                  = order.number_of_passengers
        .col-md-3
          %table.table.table-hover.table-striped
            %thead
              %tr
                %th
                  = Order.human_attribute_name(:length_of_route)
              %tbody
                %td.center
                  = order.length_of_route

app/views/orders/show.html.haml
=breadcrumb_tag do
  %li.active
    = @order.id
  %li
    = link_to 'Заказы', orders_path
  %li
    Таксопарк

%h1= @order.id

.alert.alert-info
  .row
    .col-md-1
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th
              = Order.human_attribute_name(:id)
          %tbody
            %td.center
              = @order.id
    .col-md-5
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th
              = Order.human_attribute_name(:time_of_travel)
          %tbody
            %td.center
              = @order.time_of_travel
    .col-md-6
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th
              = Order.human_attribute_name(:automobile_id)
          %tbody
            %td.center
              = "#{@order.automobile.automobile_model}, #{@order.automobile.state_number} [#{@order.automobile.automobile_type}]"
  .row
    .col-md-6
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th
              = Order.human_attribute_name(:departure_address)
          %tbody
            %td.center
              = @order.departure_address
    .col-md-6
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th
              = Order.human_attribute_name(:arrival_address)
          %tbody
            %td.center
              = @order.arrival_address
  .row
    .col-md-5
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th
              = Order.human_attribute_name(:tariff_id)
          %tbody
            %td.center
              = "#{@order.tariff.name}: #{@order.tariff.time_of_day}, #{@order.tariff.range}, #{@order.tariff.price_per_kilometer} руб./км"
    .col-md-4
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th
              = Order.human_attribute_name(:number_of_passengers)
          %tbody
            %td.center
              = @order.number_of_passengers
    .col-md-3
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th
              = Order.human_attribute_name(:length_of_route)
          %tbody
            %td.center
              = @order.length_of_route