config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  resources :orders do
    collection do
      get :search
    end
  end
  resources :tariffs
  resources :automobiles
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/automobile.rb
class Automobile < ActiveRecord::Base
  has_many :drivers, dependent: :destroy
  has_many :orders

  validates :automobile_model, length: {minimum: 5, maximum: 30}
  validates :automobile_type, inclusion: {in: ["Бизнес", "Эконом"]}
  validates :state_number, format: {with: /(а|в|е|к|м|н|о|р|с|т|у|х){2}\d{3}\d{2,3}\Z/}, uniqueness: true
  validates :color, presence: true, length: {maximum: 20}
  validates :release, numericality: {greater_than_or_equal_to: 1900, less_than_or_equal_to: Date.today.year}
end

app/controllers/automobiles_controller.rb
class AutomobilesController < ApplicationController
  before_action :set_automobile, only: [:show, :edit, :update, :destroy]

  # GET /automobiles
  # GET /automobiles.json
  def index
    @automobiles = Automobile.all
  end

  # GET /automobiles/1
  # GET /automobiles/1.json
  def show
  end

  # GET /automobiles/new
  def new
    @automobile = Automobile.new
  end

  # GET /automobiles/1/edit
  def edit
  end

  # POST /automobiles
  # POST /automobiles.json
  def create
    @automobile = Automobile.new(automobile_params)

    respond_to do |format|
      if @automobile.save
        format.html { redirect_to @automobile, notice: 'Automobile was successfully created.' }
        format.json { render :show, status: :created, location: @automobile }
      else
        format.html { render :new }
        format.json { render json: @automobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /automobiles/1
  # PATCH/PUT /automobiles/1.json
  def update
    respond_to do |format|
      if @automobile.update(automobile_params)
        format.html { redirect_to @automobile, notice: 'Automobile was successfully updated.' }
        format.json { render :show, status: :ok, location: @automobile }
      else
        format.html { render :edit }
        format.json { render json: @automobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /automobiles/1
  # DELETE /automobiles/1.json
  def destroy
    @automobile.destroy
    respond_to do |format|
      format.html { redirect_to automobiles_url, notice: 'Automobile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_automobile
      @automobile = Automobile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def automobile_params
      params.require(:automobile).permit(:automobile_model, :automobile_type, :state_number, :color, :release)
    end
end

app/helpers/automobiles_helper.rb
module AutomobilesHelper
end

app/views/automobiles/_form.html.haml
= form_for @automobile do |f|
  = error_messages_for @automobile
  .row
    .col-md-6
      .form-group
        = f.label :automobile_model
        = f.text_field :automobile_model, class: 'form-control'
        = f.error_messages_for(:automobile_model)
    .col-md-6
      .form-group
        = f.label :automobile_type
        = f.select :automobile_type, ["Бизнес", "Эконом"], {include_blank: true}, {class: 'form-control'}
        = f.error_messages_for(:automobile_type)
  .row
    .col-md-6
      .form-group
        = f.label :state_number
        = f.text_field :state_number, class: 'form-control'
        = f.error_messages_for(:state_number)
    .col-md-3
      .form-group
        = f.label :color
        = f.text_field :color, class: 'form-control'
        = f.error_messages_for(:color)
    .col-md-3
      .form-group
        = f.label :release
        = f.number_field :release, class: 'form-control'
        = f.error_messages_for(:release)
  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/automobiles/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.automobiles.edit')
  %li
    = link_to(@automobile.automobile_model + ": " + @automobile.state_number, @automobile)
  %li
    = link_to 'Автомобили', automobiles_path
  %li
    Таксопарк

.page-header
  %h1= t('headers.automobiles.edit')

= render 'form'

app/views/automobiles/index.html.haml
=breadcrumb_tag do
  %li.active
    Автомобили
  %li
    Таксопарк

.page-header
  %h1= t('headers.automobiles.index')

%table.table.table-hover.table-striped
  %caption
    = link_to new_automobile_path, class: 'btn btn-success' do
      = fa_icon :plus
      = t('buttons.new.automobile')
  %thead
    %tr
      %th= Automobile.human_attribute_name(:automobile_model)
      %th= Automobile.human_attribute_name(:automobile_type)
      %th= Automobile.human_attribute_name(:state_number)
      %th= Automobile.human_attribute_name(:color)
      %th= Automobile.human_attribute_name(:release)
      %th

  %tbody
    - @automobiles.each do |automobile|
      %tr
        %td.center= automobile.automobile_model
        %td.center= automobile.automobile_type
        %td.center= automobile.state_number
        %td.center= automobile.color
        %td.center= automobile.release
        %td.right
          = link_to automobile, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          = link_to edit_automobile_path(automobile), class: 'btn btn-info' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to automobile, :method => :delete,
          :data => { :confirm => t('buttons.confirm.automobile') },
          class: 'btn btn-danger' do
            = fa_icon :times
            = t('buttons.destroy')

app/views/automobiles/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.automobiles.new')
  %li
    = link_to 'Автомобили', automobiles_path
  %li
    Таксопарк

.page-header
  %h1= t('headers.automobiles.new')

= render 'form'

app/views/automobiles/show.html.haml
=breadcrumb_tag do
  %li.active
    = @automobile.automobile_model + ": " + @automobile.state_number
  %li
    = link_to 'Автомобили', automobiles_path
  %li
    Таксопарк

%h1= @automobile.automobile_model + ": " + @automobile.state_number

%dl
  %dt= Automobile.human_attribute_name(:automobile_model)
  %dd= @automobile.automobile_model
  %dt= Automobile.human_attribute_name(:automobile_type)
  %dd= @automobile.automobile_type
  %dt= Automobile.human_attribute_name(:state_number)
  %dd= @automobile.state_number
  %dt= Automobile.human_attribute_name(:color)
  %dd= @automobile.color
  %dt= Automobile.human_attribute_name(:release)
  %dd= @automobile.release